add -b basedir option

diff --git a/bin/bitpocket b/bin/bitpocket
--- a/bin/bitpocket
+++ b/bin/bitpocket
@@ -15,6 +15,7 @@ TMP_DIR="$DOT_DIR/tmp"
 STATE_DIR="$DOT_DIR/state"
 LOCK_DIR="$TMP_DIR/lock"  # Use a lock directory for atomic locks. See the Bash FAQ http://mywiki.wooledge.org/BashFAQ/045
 
+
 # Default settings
 SLOW_SYNC_TIME=10
 SLOW_SYNC_FILE="$TMP_DIR/slow"
@@ -28,6 +29,74 @@ REMOTE_MOUNTPOINT=false
 COMMANDS=()
 ARGS=()
 OPTIONS=()
+function usage {
+  cat <<EOF  
+usage:  bitpocket { init [<REMOTE_HOST>] <REMOTE_PATH>
+                  | sync | help | pack | log | cron | list }
+
+Available commands:
+   sync    Run the sync process. If no command is specified, sync is run by
+           default.
+   init    Initialize a new bitpocket folder. Requires path and optional
+           remote host params. Remote path must already exist.
+   pack    Pack any existing (automatic) backups into a git repository.
+   cron    Run sync optimized for cron, logging output to file instead of
+           stdout.
+   log     Display the log generated by the cron command
+   list    List all files in the sync set (honoring include/exclude/filter
+           config).
+   help    Show this message.
+
+Options:
+   -f, --force      Clean up stale lock files automatically
+   -p, --pretend    Don't really perform the sync or update the current
+                    state. Instead, show what would be synchronized.
+   -b, --base       base dir
+
+Note: All commands (apart from help), must be run in the root of a
+      new or existing bitpocket directory structure.
+EOF
+}
+
+function parseargs() {
+    while [[ -n $1 ]]; do
+        case $1 in
+            # Switches and configuration
+            -p|--pretend)   OPTIONS+=('pretend');;
+            -f|--force)     OPTIONS+=('force');;
+	    -b|--basedir)   if [[ $# -lt 2 ]] ; then
+		    		usage
+				exit 128
+			    fi
+		            BASEDIR=$2
+		            shift
+		            cd $BASEDIR || exit 1
+		            ;;	    
+            -h|--help|-*)   COMMANDS+=('help');;
+            # Arguments (commands)
+            init)           if [[ $# -lt 2 ]]; then
+                                echo "usage: bitpocket init [<REMOTE_HOST>] <REMOTE_PATH>"
+                                exit 128
+                            fi
+                            COMMANDS+=("$1")
+                            ARGS+=("$2")
+                            if [[ $# -gt 2 ]]; then
+                                ARGS+=("$3")
+                                shift;
+                            fi
+                            shift;;
+            sync|pack|cron|log|list|help)
+                            COMMANDS+=("$1");;
+            # Anything else
+            *)              echo "!!! Invalid command: $1"
+	    		    exit 1;;
+        esac
+        shift
+    done
+}
+
+parseargs "$@"
+
 
 # Load config file
 [[ -f "$CFG_FILE" ]] && . "$CFG_FILE"
@@ -751,63 +820,6 @@ function list {
       | sort
 }
 
-function usage {
-  cat <<EOF  
-usage:  bitpocket { init [<REMOTE_HOST>] <REMOTE_PATH>
-                  | sync | help | pack | log | cron | list }
-
-Available commands:
-   sync    Run the sync process. If no command is specified, sync is run by
-           default.
-   init    Initialize a new bitpocket folder. Requires path and optional
-           remote host params. Remote path must already exist.
-   pack    Pack any existing (automatic) backups into a git repository.
-   cron    Run sync optimized for cron, logging output to file instead of
-           stdout.
-   log     Display the log generated by the cron command
-   list    List all files in the sync set (honoring include/exclude/filter
-           config).
-   help    Show this message.
-
-Options:
-   -f, --force      Clean up stale lock files automatically
-   -p, --pretend    Don't really perform the sync or update the current
-                    state. Instead, show what would be synchronized.
-
-Note: All commands (apart from help), must be run in the root of a
-      new or existing bitpocket directory structure.
-EOF
-}
-
-function parseargs() {
-    while [[ -n $1 ]]; do
-        case $1 in
-            # Switches and configuration
-            -p|--pretend)   OPTIONS+=('pretend');;
-            -f|--force)     OPTIONS+=('force');;
-            -h|--help|-*)   COMMANDS+=('help');;
-            # Arguments (commands)
-            init)           if [[ $# -lt 2 ]]; then
-                                echo "usage: bitpocket init [<REMOTE_HOST>] <REMOTE_PATH>"
-                                exit 128
-                            fi
-                            COMMANDS+=("$1")
-                            ARGS+=("$2")
-                            if [[ $# -gt 2 ]]; then
-                                ARGS+=("$3")
-                                shift;
-                            fi
-                            shift;;
-            sync|pack|cron|log|list|help)
-                            COMMANDS+=("$1");;
-            # Anything else
-            *)              echo "!!! Invalid command: $1";;
-        esac
-        shift
-    done
-}
-
-parseargs "$@"
 
 # By default, run the sync process
 [[ ${#COMMANDS} == 0 ]] && COMMANDS+=('sync')
