cli: Add --pretend option
Along with an option parser. Requires Bash 4.0 or greater for associative
arrays. My guess is that by now everybody is using it?

diff --git a/bin/bitpocket b/bin/bitpocket
--- a/bin/bitpocket
+++ b/bin/bitpocket
@@ -19,6 +19,11 @@ SLOW_SYNC_TIME=10
 SLOW_SYNC_FILE="$TMP_DIR/slow"
 RSYNC_RSH="ssh"
 
+# Default command-line options and such
+COMMANDS=()
+ARGS=()
+OPTIONS=()
+
 # Load config file
 [ -f "$CFG_FILE" ] && . "$CFG_FILE"
 
@@ -187,19 +192,7 @@ function push() {
   | sed "s/^/  | /" || die "PUSH"
 }
 
-# Do the actual synchronization
-function sync {
-  assert_dotdir
-  acquire_lock
-  acquire_remote_lock
-
-  echo
-  echo -e "\x1b\x5b1;32mbitpocket started\x1b\x5b0m at `date`."
-  echo
-
-  # Fire off slow sync start notifier in background
-  on_slow_sync_start
-
+function analyse {
   # Check what has changed
   touch "$STATE_DIR/tree-prev"
 
@@ -243,20 +236,43 @@ function sync {
     wait $remote_tree_pid
     comm -23 "$STATE_DIR/tree-prev" "$STATE_DIR/remote-tree-current" > "$TMP_DIR/remote-del"
   fi
+}
+
+# Do the actual synchronization
+function sync {
+  assert_dotdir
+  acquire_lock
+  acquire_remote_lock
+
+  echo
+  echo -e "\x1b\x5b1;32mbitpocket started\x1b\x5b0m at `date`."
+  echo
+
+  # Fire off slow sync start notifier in background
+  on_slow_sync_start
+
+  # Build addtion/deletion lists
+  analyse
+
+  if [[ $OPTIONS =~ pretend ]]; then
+      RSYNC_OPTS="${RSYNC_OPTS} --dry-run"
+  fi
 
   pull
   push
 
-  # Save after-sync state
+  if [[ ! $OPTIONS =~ pretend ]]; then
+      # Save after-sync state
 
-  # Generate a incremental snapshot of the local tree including files deleted
-  # and added via the pull()
-  sort "$TMP_DIR/tree-after" \
-  | comm -13 "$TMP_DIR/pull-delete" - \
-  | sed -e "s:^\s*::" -e "s:/\$::" \
-  > "$STATE_DIR/tree-prev"
+      # Generate a incremental snapshot of the local tree including files deleted
+      # and added via the pull()
+      sort "$TMP_DIR/tree-after" \
+      | comm -13 "$TMP_DIR/pull-delete" - \
+      | sed -e "s:^\s*::" -e "s:/\$::" \
+      > "$STATE_DIR/tree-prev"
 
-  rm "$TMP_DIR/tree-after"
+      rm "$TMP_DIR/tree-after"
+  fi
 
   # Fire off slow sync stop notifier in background
   on_slow_sync_stop
@@ -429,42 +445,61 @@ function list {
 }
 
 function usage {
-  echo "usage:  bitpocket [sync|help|pack|log|cron|list|init <REMOTE_HOST> <REMOTE_PATH>]"
-  echo ""
-  echo "Available commands:"
-  echo "   sync    Run the sync process. If no command is specified, sync is run by default."
-  echo "   init    Initialize a new bitpocket folder. Requires remote host and path params."
-  echo "   pack    Pack any existing (automatic) backups into a git repository."
-  echo "   cron    Run sync optimized for cron, logging output to file instead of stdout."
-  echo "   log     Display the log generated by the cron command"
-  echo "   list    List all files in the sync set (honoring include/exclude/filter config)."
-  echo "   help    Show this message."
-  echo ""
-  echo "Note: All commands (apart from help), must be run in the root of a"
-  echo "      new or existing bitpocket directory structure."
-  echo ""
+  cat <<EOF  
+usage:  bitpocket [sync|help|pack|log|cron|list|init <REMOTE_HOST> <REMOTE_PATH>]
 
+Available commands:
+   sync    Run the sync process. If no command is specified, sync is run by default.
+   init    Initialize a new bitpocket folder. Requires remote host and path params.
+   pack    Pack any existing (automatic) backups into a git repository.
+   cron    Run sync optimized for cron, logging output to file instead of stdout.
+   log     Display the log generated by the cron command
+   list    List all files in the sync set (honoring include/exclude/filter config).
+   help    Show this message.
+
+Options:
+   -p, --pretend    Don't really perform the sync or update the current
+                    state. Instead, show what would be synchronized.
+
+Note: All commands (apart from help), must be run in the root of a
+      new or existing bitpocket directory structure.
+EOF
 }
 
-if [ "$1" = "init" ]; then
-  # Initialize bitpocket directory
-  init $2 "$3" $4
-elif [ "$1" = "pack" ]; then
-  # Pack backups using git
-  pack
-elif [ "$1" = "log" ]; then
-  # Display log file
-  log
-elif [ "$1" = "cron" ]; then
-  # Run through cron?
-  cron
-elif [ "$1" = "list" ]; then
-  # List all file in sync set (honoring .bitpocket/include & .bitpocket/exclude)
-  list
-elif [ "$1" != "" ] && [ "$1" != "sync" ]; then
-  # Show help
-  usage
-else
-  # By default, run the sync process
-  sync
-fi
+function parseargs() {
+    while [[ -n $1 ]]; do
+        case $1 in
+            # Switches and configuration
+            -p|--pretend)   OPTIONS+=('pretend');;
+            -h|--help|-*)   COMMANDS+=('help');;
+            # Arguments (commands)
+            init)           if [[ $# < 3 ]]; then
+                                echo "usage: bitpocket init <REMOTE_HOST> <REMOTE_PATH>"
+                                exit 128
+                            fi
+                            COMMANDS+=($1)
+                            ARGS+=($2 "$3")
+                            shift; shift;;
+            sync|init|pack|cron|log|list|help)
+                            COMMANDS+=($1);;
+            *)              echo "!!! Invalid command: $1";;
+        esac
+        shift
+    done
+}
+
+parseargs $*
+
+# By default, run the sync process
+[[ ${#COMMANDS} == 0 ]] && COMMANDS+=('sync')
+
+# For now, only one command really makes sense
+case ${COMMANDS[0]} in
+    init)       init "${ARGS[@]}";;
+    pack)       pack;;
+    log)        log;;
+    cron)       cron;;
+    list)       list;;
+    help)       usage;;
+    sync)       sync;;
+esac
