add remote lock handling with rsync only

diff --git a/bin/bitpocket b/bin/bitpocket
--- a/bin/bitpocket
+++ b/bin/bitpocket
@@ -8,11 +8,13 @@ fi
 
 export LC_ALL=$LANG # for stable "sort" output
 
+REMOTE_LOCK_NAME=remotelock
 # Paths
 DOT_DIR=.bitpocket
 CFG_FILE="$DOT_DIR/config"
 TMP_DIR="$DOT_DIR/tmp"
 STATE_DIR="$DOT_DIR/state"
+REMOTE_LOCK_DIR="$DOT_DIR/$REMOTE_LOCK_NAME"
 LOCK_DIR="$TMP_DIR/lock"  # Use a lock directory for atomic locks. See the Bash FAQ http://mywiki.wooledge.org/BashFAQ/045
 
 
@@ -21,10 +23,13 @@ SLOW_SYNC_TIME=10
 SLOW_SYNC_FILE="$TMP_DIR/slow"
 RSYNC_RSH="ssh"
 [ "$RSYNC_SSH_OPTIONS" = "" ] && RSYNC_SSH_OPTIONS="ssh"
+[ "$REMOTE_LOCK_WAIT" = "" ] && REMOTE_LOCK_WAIT=1
+[ "$REMOTE_LOCK_TIMEOUT" = "" ] && REMOTE_LOCK_TIMEOUT=1800
 REMOTE_BACKUPS=false
 BACKUPS=true
 LOCAL_MOUNTPOINT=false
 REMOTE_MOUNTPOINT=false
+NO_SSH=false
 
 # Default command-line options and such
 COMMANDS=()
@@ -53,6 +58,7 @@ Options:
    -p, --pretend    Don't really perform the sync or update the current
                     state. Instead, show what would be synchronized.
    -b, --base       base dir
+   -n, --nossh      omit ssh calls - only use rsync (no remote locking)
 
 Note: All commands (apart from help), must be run in the root of a
       new or existing bitpocket directory structure.
@@ -65,14 +71,15 @@ function parseargs() {
             # Switches and configuration
             -p|--pretend)   OPTIONS+=('pretend');;
             -f|--force)     OPTIONS+=('force');;
-	    -b|--basedir)   if [[ $# -lt 2 ]] ; then
-		    		usage
-				exit 128
-			    fi
-		            BASEDIR=$2
-		            shift
-		            cd $BASEDIR || exit 1
-		            ;;	    
+            -n|--nossh)     NO_SSH=true;;
+        -b|--basedir)   if [[ $# -lt 2 ]] ; then
+                    usage
+                exit 128
+                fi
+                    BASEDIR=$2
+                    shift
+                    cd $BASEDIR || exit 1
+                    ;;      
             -h|--help|-*)   COMMANDS+=('help');;
             # Arguments (commands)
             init)           if [[ $# -lt 2 ]]; then
@@ -90,7 +97,7 @@ function parseargs() {
                             COMMANDS+=("$1");;
             # Anything else
             *)              echo "!!! Invalid command: $1"
-	    		    exit 1;;
+                    exit 1;;
         esac
         shift
     done
@@ -171,6 +178,7 @@ fi
 USER_RULES="$user_filter $user_include $user_exclude"
 
 TIMESTAMP=$(date "+%Y-%m-%d.%H%M%S")
+LOCK_TIMESTAMP=$(date "+%s")
 
 export RSYNC_RSH
 
@@ -193,10 +201,18 @@ function init {
 
   REMOTE_PATH="$1"
   setup_remote
-  #if $REMOTE_RUNNER "[ ! -d '$1' ]"; then
-  #  echo "fatal: '$REMOTE': Remote path is not accessible"
-  #  exit 128
-  #fi
+  if [ "$NO_SSH" != true ] ; then
+    if $REMOTE_RUNNER "[ ! -d '$1' ]"; then
+      echo "fatal: '$REMOTE': Remote path is not accessible"
+      exit 128
+    fi
+  else
+    rsync -e "$RSYNC_SSH_OPTIONS" $RSYNC_OPTS --list-only --include="." --exclude="**" "$REMOTE/"
+    if [ $? != 0 ] ; then
+        echo "fatal: $REMOTE: remote not accessible"
+        exit 128
+    fi
+  fi
 
   mkdir "$DOT_DIR"
 
@@ -205,6 +221,7 @@ function init {
 REMOTE_HOST=$REMOTE_HOST
 REMOTE_PATH="$REMOTE_PATH"
 RSYNC_SSH_OPTIONS="$RSYNC_SSH_OPTIONS"
+NO_SSH="$NO_SSH"
 
 ## Backups -----------------------------------
 ## Enable file revisioning locally in the pull phase (>false< to disable)
@@ -498,7 +515,11 @@ function sync {
   assert_dotdir
   assert_mountpoints
   acquire_lock
-  #acquire_remote_lock
+  if [ "$NO_SSH"  = true ] ; then
+      acquire_remote_lock_rsync
+  else
+      acquire_remote_lock
+  fi
   check_state_version
   detect_fatfs
 
@@ -658,7 +679,95 @@ function acquire_lock {
 function release_lock {
   rm "$LOCK_DIR/pid" &>/dev/null && rmdir "$LOCK_DIR" &>/dev/null
 }
+function filter_outdated(){
+    while read -r line
+    do
+        IFS=":" read -ra info <<< "$line"
+        if [ "${info[2]}" -gt "$1" ] ; then
+            echo "$line"
+        fi    
+    done
+}
+#read the remote locks
+#return locks in the file REMOTE_STATE
+#return 0 if our own only, 1 if other, -1 if own not there
+#p1 our own lock file name
+#TODO: handle timeouts for locks
+function read_remote_locks() {
+    REMOTE_STATE="$STATE_DIR/remote-state"
+    local old_ts=$(date "+%s")
+    let "old_ts=$old_ts-$REMOTE_LOCK_TIMEOUT"
+    rm -f "$REMOTE_STATE"
+    rsync -e "$RSYNC_SSH_OPTIONS" $RSYNC_OPTS -r --list-only --filter="+ $DOT_DIR" --filter="+ $REMOTE_LOCK_DIR" --filter="+ $REMOTE_LOCK_DIR/*" --filter="- *" $REMOTE/ | sed -n "s?.*$REMOTE_LOCK_DIR/??p" | sed '/^ *$/d' > "$REMOTE_STATE"
+    [ $? != 0 ] && return -2
+    grep "$1" "$REMOTE_STATE" > /dev/null 2>&1
+    [ $? != 0 ] && return -1
+    local n=`cat "$REMOTE_STATE" | filter_outdated $old_ts | wc -l`
+    [ $n -gt 1 ] && return 1
+    return 0    
+}
 
+function acquire_remote_lock_rsync {
+    #write our own lock file to the remote
+    #and check if we are the only one
+    #consider the REMOTE_LOCK_TIMEOUT and REMOTE_LOCK_WAIT
+    local INFO="$HOSTNAME:$$:$LOCK_TIMESTAMP"
+    if [ -d $REMOTE_LOCK_DIR ] ; then
+        rm -rf $REMOTE_LOCK_DIR
+        mkdir -p $REMOTE_LOCK_DIR
+        touch $REMOTE_LOCK_DIR/$INFO
+    fi    
+    #write our lockfile to remote
+    echo "#creating remote lock $REMOTE_LOCK_DIR/$INFO"
+    rsync  -e "$RSYNC_SSH_OPTIONS" $RSYNC_OPTS -ra  --filter="+ $DOT_DIR" --filter="+ $REMOTE_LOCK_DIR" --filter="+ $REMOTE_LOCK_DIR/$INFO" --filter="- *" ./ $REMOTE/
+    
+    read_remote_locks "$INFO"
+    local rstate=$?
+    [ $rstate = 0 ] && return 0
+    if [ "$rstate" -ne 1 ] ; then
+        die "unable to acquire remote lock"
+    fi
+    local wait_time=0
+    while [ $wait_time -lt "$REMOTE_LOCK_WAIT" ] 
+    do
+        local other_hosts=`cat "$REMOTE_STATE" | grep -v "^$HOSTNAME:"`
+        if [ "$other_hosts" != "" ] ; then
+            echo "other hosts having locks: $other_hosts"
+        else    
+            local pids_same_host=`cat "$REMOTE_STATE" | grep -v "$INFO" | sed -n "s?^$HOSTNAME:??p" | sed 's/:.*//'`
+            if [ "$pids_same_host" != "" ] ; then
+                echo "found pids: $pids_same_host from our host, checking"
+                local all_stopped=1
+                for pid in $pids_same_host
+                do
+                    kill -0 $pid > /dev/null 2>&1
+                    if [ $? = 0 ] ; then
+                        all_stopped=0
+                        break
+                    fi
+                done
+                if [ $all_stopped = 1 ] ; then
+                    echo "locks from our host found without process, ignoring"
+                    return 0
+                fi
+            fi
+        fi    
+        sleep 1
+        let "wait_time=$wait_time+1"
+        echo "waiting for remote lock"
+        read_remote_locks "$INFO"
+        rstate=$?
+        [ $rstate = 0 ] && return 0
+        if [ "$rstate" -ne 1 ] ; then
+            die "unable to acquire remote lock"
+        fi
+    done    
+    local code=3
+    echo -e "${YELLOW}Another client is syncing with '$REMOTE'${CLEAR}"
+    cat $REMOTE_STATE | grep -v "$INFO"
+    cleanup
+    exit $code
+}
 function acquire_remote_lock {
     # TODO: Place the local hostname and this PID in a file, which will make
     # automatic lock file cleanup possible. It will also offer better output if
@@ -712,10 +821,17 @@ function acquire_remote_lock {
         fi
     fi
 
-    release_lock
+    cleanup
     exit $code
 }
 
+function release_remote_lock_rsync {
+    rm -rf $REMOTE_LOCK_DIR
+    mkdir -p $REMOTE_LOCK_DIR
+    local INFO="$HOSTNAME:$$:$LOCK_TIMESTAMP"
+    echo "#releasing remote lock $REMOTE_LOCK_DIR/$INFO"
+    rsync -e "$RSYNC_SSH_OPTIONS" $RSYNC_OPTS -ra --delete --filter="+ $DOT_DIR" --filter="+ $REMOTE_LOCK_DIR" --filter="+ $REMOTE_LOCK_DIR/$INFO" --filter="- *" ./ $REMOTE/
+}
 function release_remote_lock {
   $REMOTE_RUNNER "cd \"$REMOTE_PATH\" && grep -q '$HOSTNAME:$$' '$LOCK_DIR/remote' && rm '$LOCK_DIR/remote' && rmdir '$LOCK_DIR' &>/dev/null"
 }
@@ -773,7 +889,11 @@ function assert_mountpoints {
 
 function cleanup {
   release_lock
-  #release_remote_lock
+  if [ "$NO_SSH" = true ] ; then
+      release_remote_lock_rsync
+  else
+      release_remote_lock
+  fi    
 }
 
 ##
